# Pre-Processamento

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

pd.set_option('display.max_columns', 999)
pd.set_option('display.max_rows', 999)

In [2]:
csv_path = '../Data/'

market = pd.read_csv(f'{csv_path}estaticos_market.csv', index_col='Unnamed: 0')
port1 = pd.read_csv(f'{csv_path}estaticos_portfolio1.csv', index_col='Unnamed: 0')
port2 = pd.read_csv(f'{csv_path}estaticos_portfolio2.csv', index_col='Unnamed: 0')
port3 = pd.read_csv(f'{csv_path}estaticos_portfolio3.csv', index_col='Unnamed: 0')

ids = market['id']

port2 = port2.merge(market,on='id')
port3 = port3.merge(market,on='id')

In [3]:
market.head(4)

,id,fl_matriz,de_natureza_juridica,sg_uf,natureza_juridica_macro,de_ramo,setor,idade_empresa_anos,idade_emp_cat,fl_me,fl_sa,fl_epp,fl_mei,fl_ltda,dt_situacao,fl_st_especial,fl_email,fl_telefone,fl_rm,nm_divisao,nm_segmento,fl_spa,fl_antt,fl_veiculo,vl_total_tancagem,vl_total_veiculos_antt,vl_total_veiculos_leves,vl_total_veiculos_pesados,fl_optante_simples,qt_art,vl_total_veiculos_pesados_grupo,vl_total_veiculos_leves_grupo,vl_total_tancagem_grupo,vl_total_veiculos_antt_grupo,vl_potenc_cons_oleo_gas,fl_optante_simei,sg_uf_matriz,de_saude_tributaria,de_saude_rescencia,nu_meses_rescencia,de_nivel_atividade,de_indicador_telefone,fl_simples_irregular,vl_frota,empsetorcensitariofaixarendapopulacao,nm_meso_regiao,nm_micro_regiao,fl_passivel_iss,qt_socios,qt_socios_pf,qt_socios_pj,idade_media_socios,idade_maxima_socios,idade_minima_socios,qt_socios_st_regular,qt_socios_st_suspensa,qt_socios_masculino,qt_socios_feminino,qt_socios_pep,qt_alteracao_socio_total,qt_alteracao_socio_90d,qt_alteracao_socio_180d,qt_alteracao_socio_365d,qt_socios_pj_ativos,qt_socios_pj_nulos,qt_socios_pj_baixados,qt_socios_pj_suspensos,qt_socios_pj_inaptos,vl_idade_media_socios_pj,vl_idade_maxima_socios_pj,vl_idade_minima_socios_pj,qt_coligados,qt_socios_coligados,qt_coligados_matriz,qt_coligados_ativo,qt_coligados_baixada,qt_coligados_inapta,qt_coligados_suspensa,qt_coligados_nula,idade_media_coligadas,idade_maxima_coligadas,idade_minima_coligadas,coligada_mais_nova_ativa,coligada_mais_antiga_ativa,idade_media_coligadas_ativas,coligada_mais_nova_baixada,coligada_mais_antiga_baixada,idade_media_coligadas_baixadas,qt_coligados_sa,qt_coligados_me,qt_coligados_mei,qt_coligados_ltda,qt_coligados_epp,qt_coligados_norte,qt_coligados_sul,qt_coligados_nordeste,qt_coligados_centro,qt_coligados_sudeste,qt_coligados_exterior,qt_ufs_coligados,qt_regioes_coligados,qt_ramos_coligados,qt_coligados_industria,qt_coligados_agropecuaria,qt_coligados_comercio,qt_coligados_servi√ßo,qt_coligados_ccivil,qt_funcionarios_coligados,qt_funcionarios_coligados_gp,media_funcionarios_coligados_gp,max_funcionarios_coligados_gp,min_funcionarios_coligados_gp,vl_folha_coligados,media_vl_folha_coligados,max_vl_folha_coligados,min_vl_folha_coligados,vl_folha_coligados_gp,media_vl_folha_coligados_gp,max_vl_folha_coligados_gp,min_vl_folha_coligados_gp,faturamento_est_coligados,media_faturamento_est_coligados,max_faturamento_est_coligados,min_faturamento_est_coligados,faturamento_est_coligados_gp,media_faturamento_est_coligados_gp,max_faturamento_est_coligados_gp,min_faturamento_est_coligados_gp,total_filiais_coligados,media_filiais_coligados,max_filiais_coligados,min_filiais_coligados,qt_coligados_atividade_alto,qt_coligados_atividade_medio,qt_coligados_atividade_baixo,qt_coligados_atividade_mt_baixo,qt_coligados_atividade_inativo,qt_coligadas,sum_faturamento_estimado_coligadas,de_faixa_faturamento_estimado,de_faixa_faturamento_estimado_grupo,vl_faturamento_estimado_aux,vl_faturamento_estimado_grupo_aux,qt_ex_funcionarios,qt_funcionarios_grupo,percent_func_genero_masc,percent_func_genero_fem,idade_ate_18,idade_de_19_a_23,idade_de_24_a_28,idade_de_29_a_33,idade_de_34_a_38,idade_de_39_a_43,idade_de_44_a_48,idade_de_49_a_53,idade_de_54_a_58,idade_acima_de_58,grau_instrucao_macro_analfabeto,grau_instrucao_macro_escolaridade_fundamental,grau_instrucao_macro_escolaridade_media,grau_instrucao_macro_escolaridade_superior,grau_instrucao_macro_desconhecido,total,meses_ultima_contratacaco,qt_admitidos_12meses,qt_desligados_12meses,qt_desligados,qt_admitidos,media_meses_servicos_all,max_meses_servicos_all,min_meses_servicos_all,media_meses_servicos,max_meses_servicos,min_meses_servicos,qt_funcionarios,qt_funcionarios_12meses,qt_funcionarios_24meses,tx_crescimento_12meses,tx_crescimento_24meses,tx_rotatividade,qt_filiais
0,a6984c3ae395090e3bee8ad63c3758b110de096d5d8195...,True,SOCIEDADE EMPRESARIA LIMITADA,RN,ENTIDADES EMPRESARIAIS,INDUSTRIA DA CONSTRUCAO,CONSTRU√á√ÉO CIVIL,14.457534,10 a 15,False,False,False,False,False,2005-03-25,False,True,True,SIM,CONSTRUCAO DE EDIFICIOS,CONSTRUCAO,False,False,False,NaN,NaN,NaN,NaN,True,8.0,0.0,0.0,NaN,NaN,NaN,False,RN,VERDE,ACIMA DE 1 ANO,23.0,ALTA,BOA,False,NaN,NaN,LESTE POTIGUAR,NATAL,True,2.0,2.0,0.0,44.0,47.0,41.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,8.0,6.0,6.0,0.0,0.0,0.0,0.0,220.477778,536.366667,57.3,57.3,536.366667,220.477778,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,2.0,1.0,5.0,0.0,0.0,1.0,5.0,0.0,145.0,145.0,36.25,91.0,6.0,9375912.0,2343978.0,5275238.5,638798.4,9375912.0,2343978.0,5275238.5,638798.4,21809443.0,3.634907e+06,13188096.0,210000.0,22019443.0,3.669907e+06,13188096.0,210000.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,6.0,21809443.0,"DE R$ 1.500.000,01 A R$ 4.800.000,00","DE R$ 1.500.000,01 A R$ 4.800.000,00",3132172.8,3132172.8,119.0,26.0,100.0,0.0,NaN,1.0,4.0,6.0,5.0,3.0,4.0,2.0,NaN,1.0,NaN,1.0,25.0,NaN,NaN,26.0,19.166667,0.0,0.0,119.0,145.0,13.309195,93.266667,-0.933333,43.738462,93.266667,19.166667,26.0,26.0,27.0,0.0,-3.703704,0.0,0
1,6178f41ade1365e44bc2c46654c2c8c0eaae27dcb476c4...,True,EMPRESARIO INDIVIDUAL,PI,OUTROS,SERVICOS DE ALOJAMENTO/ALIMENTACAO,SERVI√áO,1.463014,1 a 5,False,False,False,True,False,2017-05-12,False,True,True,SIM,ALIMENTACAO,ALOJAMENTO E ALIMENTACAO,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,PI,CINZA,ATE 1 ANO,9.0,BAIXA,NaN,False,NaN,468.93,CENTRO NORTE PIAUIENSE,TERESINA,True,1.0,1.0,0.0,27.0,27.0,27.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DE R$ 81.000,01 A R$ 360.000,00","DE R$ 81.000,01 A R$ 360.000,00",210000.0,210000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,4a7e5069a397f12fdd7fd57111d6dc5d3ba558958efc02...,True,EMPRESARIO INDIVIDUAL,AM,OUTROS,"TRANSPORTE, ARMAZENAGEM E CORREIO",SERVI√áO,7.093151,5 a 10,False,False,False,True,False,2011-09-26,False,False,True,SIM,TRANSPORTE TERRESTRE,TRANSPORTE ARMAZENAGEM E CORREIO,False,False,False,NaN,NaN,NaN,NaN,True,NaN,0.0,0.0,NaN,NaN,NaN,True,AM,AMARELO,ACIMA DE 1 ANO,26.0,MEDIA,NaN,False,NaN,713.50,CENTRO AMAZONENSE,MANAUS,True,1.0,1.0,0.0,32.0,32.0,32.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ATE R$ 81.000,00","ATE R$ 81.000,00",50000.0,50000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,3348900fe63216a439d2e5238c79ddd46ede454df7b9d8...,True,EMPRESARIO INDIVIDUAL,AM,OUTROS,SERVICOS DIVERSOS,SERVI√áO,6.512329,5 a 10,False,False,False,False,False,2012-04-25,False,True,True,SIM,REPARACAO E MANUTENCAO DE EQUIPAMENTOS DE INFO...,OUTRAS ATIVIDADES DE SERVICOS,False,False,False,NaN,NaN,NaN,NaN,True,NaN,0.0,0.0,NaN,NaN,NaN,False,AM,AMARELO,ACIMA DE 1 ANO,26.0,MEDIA,NaN,False,NaN,475.73,CENTRO AMAZONENSE,MANAUS,True,1.0,1.0,0.0,36.0,36.0,36.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DE R$ 81.000,01 A R$ 360.000,00","DE R$ 81.000,01 A R$ 360.000,00",210000.0,210000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [4]:
print(f'Market: {market.shape}')
print(f'Portfolio 1 {port1.shape}')
print(f'Portfolio 2: {port2.shape}')
print(f'Portfolio 3: {port3.shape}')

Market: (462298, 181)
Portfolio 1 (555, 181)
Portfolio 2: (566, 181)
Portfolio 3: (265, 181)

### Dropando features redundantes

In [5]:
features_redundantes = ['de_ramo', 'de_natureza_juridica','idade_emp_cat',
                     'nm_divisao','nm_micro_regiao','de_faixa_faturamento_estimado',
                     'de_faixa_faturamento_estimado_grupo','dt_situacao','de_saude_rescencia',
                       'idade_maxima_socios','idade_minima_socios']

market.drop(features_redundantes, 1, inplace = True)

### DataFrame Auxiliar

In [6]:
aux = pd.DataFrame({'tipo': market.dtypes,
                    'missing': market.isna().sum(),
                    'size':market.shape[0],
                    'unicos': market.nunique()},index = market.columns)

aux['percentual'] = round(1 - (aux['missing'] / aux['size']),2)

In [7]:
aux.sort_values('percentual',ascending=False)

,tipo,missing,size,unicos,percentual
id,object,0,462298,462298,1.00
fl_telefone,bool,0,462298,2,1.00
fl_matriz,bool,0,462298,2,1.00
fl_passivel_iss,object,1927,462298,2,1.00
fl_simples_irregular,object,1927,462298,2,1.00
sg_uf_matriz,object,1939,462298,27,1.00
vl_total_veiculos_leves_grupo,float64,1927,462298,310,1.00
vl_total_veiculos_pesados_grupo,float64,1927,462298,296,1.00
fl_veiculo,object,1927,462298,2,1.00
fl_antt,object,1927,462298,2,1.00
fl_spa,object,1927,462298,2,1.00
nm_segmento,object,1927,462298,21,1.00
fl_rm,object,0,462298,2,1.00
qt_filiais,int64,0,462298,304,1.00
fl_email,bool,0,462298,2,1.00
fl_st_especial,bool,0,462298,2,1.00
natureza_juridica_macro,object,0,462298,7,1.00
setor,object,1927,462298,5,1.00
fl_me,bool,0,462298,2,1.00
fl_sa,bool,0,462298,2,1.00
idade_empresa_anos,float64,0,462298,14198,1.00
fl_ltda,bool,0,462298,2,1.00
fl_mei,bool,0,462298,2,1.00
sg_uf,object,0,462298,6,1.00
fl_epp,bool,0,462298,1,1.00
de_nivel_atividade,object,11168,462298,4,0.98
de_saude_tributaria,object,14851,462298,6,0.97
vl_faturamento_estimado_grupo_aux,float64,27513,462298,6794,0.94
vl_faturamento_estimado_aux,float64,27513,462298,1920,0.94
nu_meses_rescencia,float64,45276,462298,51,0.90
nm_meso_regiao,object,58698,462298,19,0.87
fl_optante_simples,object,82713,462298,2,0.82
fl_optante_simei,object,82713,462298,2,0.82
qt_socios_pj,float64,115091,462298,12,0.75
qt_socios_pf,float64,115091,462298,64,0.75
qt_socios,float64,115091,462298,62,0.75
empsetorcensitariofaixarendapopulacao,float64,143829,462298,15419,0.69
idade_media_socios,float64,151602,462298,1010,0.67
qt_socios_st_regular,float64,154917,462298,54,0.66
qt_socios_masculino,float64,267183,462298,41,0.42
qt_socios_feminino,float64,317269,462298,33,0.31
qt_ex_funcionarios,float64,347044,462298,1092,0.25
qt_funcionarios_grupo,float64,347035,462298,1456,0.25
qt_desligados,float64,358724,462298,1082,0.22
qt_desligados_12meses,float64,358724,462298,227,0.22
meses_ultima_contratacaco,float64,358724,462298,3657,0.22
media_meses_servicos_all,float64,358738,462298,61515,0.22
qt_admitidos_12meses,float64,358724,462298,258,0.22
qt_admitidos,float64,358724,462298,1332,0.22
max_meses_servicos_all,float64,358738,462298,7194,0.22
qt_funcionarios,float64,358724,462298,712,0.22
tx_rotatividade,float64,358724,462298,2548,0.22
qt_funcionarios_12meses,float64,358724,462298,713,0.22
qt_funcionarios_24meses,float64,358724,462298,762,0.22
min_meses_servicos_all,float64,358738,462298,3015,0.22
min_meses_servicos,float64,386037,462298,3003,0.16
percent_func_genero_fem,float64,386356,462298,2391,0.16
percent_func_genero_masc,float64,386356,462298,2391,0.16
max_meses_servicos,float64,386037,462298,5484,0.16
media_meses_servicos,float64,386037,462298,37029,0.16
tx_crescimento_12meses,float64,388410,462298,2237,0.16
total,float64,386356,462298,709,0.16
tx_crescimento_24meses,float64,388284,462298,3388,0.16
grau_instrucao_macro_escolaridade_media,float64,394501,462298,513,0.15
qt_coligados_agropecuaria,float64,396907,462298,21,0.14
qt_coligados_ccivil,float64,396907,462298,105,0.14
qt_coligados_servi√ßo,float64,396907,462298,110,0.14
qt_coligados_comercio,float64,396907,462298,56,0.14
qt_coligados_exterior,float64,396907,462298,6,0.14
qt_coligados_industria,float64,396907,462298,57,0.14
qt_regioes_coligados,float64,396907,462298,7,0.14
qt_ufs_coligados,float64,396907,462298,26,0.14
media_faturamento_est_coligados,float64,397775,462298,12108,0.14
faturamento_est_coligados,float64,397775,462298,11621,0.14
min_faturamento_est_coligados_gp,float64,397775,462298,1341,0.14
max_faturamento_est_coligados,float64,397775,462298,2296,0.14
min_faturamento_est_coligados,float64,397775,462298,722,0.14
faturamento_est_coligados_gp,float64,397775,462298,13144,0.14
media_faturamento_est_coligados_gp,float64,397775,462298,13919,0.14
max_faturamento_est_coligados_gp,float64,397775,462298,4343,0.14
qt_coligados_centro,float64,396907,462298,42,0.14
qt_coligados_atividade_alto,float64,396907,462298,1,0.14
qt_coligados_atividade_medio,float64,396907,462298,1,0.14
qt_coligados_atividade_baixo,float64,396907,462298,1,0.14
qt_coligados_atividade_mt_baixo,float64,396907,462298,1,0.14
qt_coligados_atividade_inativo,float64,396907,462298,1,0.14
qt_coligados_sudeste,float64,396907,462298,146,0.14
qt_ramos_coligados,float64,396907,462298,45,0.14
qt_coligados_nordeste,float64,396907,462298,80,0.14
idade_media_coligadas_ativas,float64,397151,462298,27923,0.14
qt_coligados,float64,396907,462298,168,0.14
qt_coligados_norte,float64,396907,462298,55,0.14
qt_socios_coligados,float64,396907,462298,273,0.14
qt_coligados_matriz,float64,396907,462298,169,0.14
qt_coligados_ativo,float64,396907,462298,171,0.14
qt_coligados_baixada,float64,396907,462298,6,0.14
qt_coligados_inapta,float64,396907,462298,12,0.14
qt_coligados_suspensa,float64,396907,462298,2,0.14
qt_coligados_nula,float64,396907,462298,1,0.14
idade_media_coligadas,float64,396907,462298,28060,0.14
idade_maxima_coligadas,float64,396907,462298,10760,0.14
idade_minima_coligadas,float64,396907,462298,8584,0.14
coligada_mais_nova_ativa,float64,397151,462298,8583,0.14
coligada_mais_antiga_ativa,float64,397151,462298,10749,0.14
qt_coligados_sul,float64,396907,462298,38,0.14
qt_coligados_me,float64,396907,462298,6,0.14
qt_coligados_epp,float64,396907,462298,5,0.14
qt_coligados_mei,float64,396907,462298,6,0.14
qt_coligados_ltda,float64,396907,462298,21,0.14
qt_coligados_sa,float64,396907,462298,65,0.14
qt_coligadas,float64,412067,462298,116,0.11
sum_faturamento_estimado_coligadas,float64,412754,462298,8828,0.11
max_funcionarios_coligados_gp,float64,419995,462298,1116,0.09
media_funcionarios_coligados_gp,float64,419995,462298,3388,0.09
qt_funcionarios_coligados_gp,float64,419995,462298,1917,0.09
qt_funcionarios_coligados,float64,419995,462298,1453,0.09
idade_de_29_a_33,float64,422155,462298,240,0.09
de_indicador_telefone,object,418405,462298,2,0.09
min_funcionarios_coligados_gp,float64,419995,462298,393,0.09
min_vl_folha_coligados,float64,425984,462298,704,0.08
idade_de_24_a_28,float64,423403,462298,186,0.08
idade_de_34_a_38,float64,425569,462298,258,0.08
max_vl_folha_coligados,float64,425984,462298,1565,0.08
vl_folha_coligados_gp,float64,425761,462298,7219,0.08
media_vl_folha_coligados,float64,425984,462298,7528,0.08
media_vl_folha_coligados_gp,float64,425761,462298,7913,0.08
max_vl_folha_coligados_gp,float64,425761,462298,1898,0.08
vl_folha_coligados,float64,425984,462298,6680,0.08
min_vl_folha_coligados_gp,float64,425761,462298,811,0.08
vl_total_veiculos_pesados,float64,431614,462298,103,0.07
vl_total_veiculos_leves,float64,431614,462298,121,0.07
idade_de_39_a_43,float64,431890,462298,243,0.07
idade_de_19_a_23,float64,436408,462298,133,0.06
grau_instrucao_macro_escolaridade_fundamental,float64,437402,462298,281,0.05
grau_instrucao_macro_escolaridade_superior,float64,439571,462298,346,0.05
vl_frota,float64,438108,462298,13833,0.05
idade_de_44_a_48,float64,438008,462298,209,0.05
total_filiais_coligados,float64,441898,462298,368,0.04
media_filiais_coligados,float64,441898,462298,755,0.04
idade_de_49_a_53,float64,443261,462298,191,0.04
min_filiais_coligados,float64,441898,462298,80,0.04
max_filiais_coligados,float64,441898,462298,180,0.04
idade_de_54_a_58,float64,448323,462298,164,0.03
idade_acima_de_58,float64,451272,462298,176,0.02
vl_idade_maxima_socios_pj,float64,457754,462298,1944,0.01
qt_socios_pj_nulos,float64,457754,462298,2,0.01
qt_socios_pj_suspensos,float64,457754,462298,3,0.01
qt_socios_st_suspensa,float64,459047,462298,4,0.01
qt_socios_pep,float64,455555,462298,31,0.01
qt_art,float64,455708,462298,120,0.01
qt_socios_pj_ativos,float64,457754,462298,11,0.01
idade_ate_18,float64,459392,462298,33,0.01
vl_idade_minima_socios_pj,float64,457754,462298,1952,0.01
qt_socios_pj_baixados,float64,457754,462298,3,0.01
qt_socios_pj_inaptos,float64,457754,462298,5,0.01
vl_potenc_cons_oleo_gas,float64,458615,462298,155,0.01
vl_idade_media_socios_pj,float64,457754,462298,2192,0.01
vl_total_tancagem_grupo,float64,460538,462298,106,0.00
vl_total_veiculos_antt_grupo,float64,461962,462298,31,0.00
vl_total_veiculos_antt,float64,462122,462298,20,0.00
vl_total_tancagem,float64,462018,462298,33,0.00
coligada_mais_antiga_baixada,float64,462162,462298,46,0.00
qt_alteracao_socio_total,float64,462298,462298,0,0.00
qt_alteracao_socio_90d,float64,462298,462298,0,0.00
qt_alteracao_socio_180d,float64,462298,462298,0,0.00
qt_alteracao_socio_365d,float64,462298,462298,0,0.00
grau_instrucao_macro_desconhecido,float64,462298,462298,0,0.00
idade_media_coligadas_baixadas,float64,462162,462298,48,0.00
coligada_mais_nova_baixada,float64,462162,462298,46,0.00
grau_instrucao_macro_analfabeto,float64,460414,462298,34,0.00

### Tratamento de valores missing:

In [8]:
market['qt_coligados'].fillna(0, inplace=True)
market['qt_socios'].fillna(1, inplace=True)
market['qt_socios_pf'].fillna(1, inplace=True)
market['qt_socios_pj'].fillna(0, inplace=True)
market['qt_funcionarios'].fillna(0, inplace=True)
market['tx_crescimento_12meses'].fillna(0, inplace=True)
market['tx_crescimento_24meses'].fillna(0, inplace=True)
market['fl_optante_simei'].fillna('False',inplace=True)
market['fl_optante_simples'].fillna('False',inplace=True)
market['nm_meso_regiao'].fillna('OUTROS',inplace=True)
market['nu_meses_rescencia'].fillna(market['nu_meses_rescencia'].median(),inplace=True)
market['vl_faturamento_estimado_aux'].fillna(market['vl_faturamento_estimado_aux'].median(),inplace=True)
market['vl_faturamento_estimado_grupo_aux'].fillna(market['vl_faturamento_estimado_aux'].median(),inplace=True) # Substituir pela mediana do faturamento estimado, pois provavelmente a empresa n√£o faz parte de um grupo
market.loc[market['sg_uf_matriz'].isna(), 'sg_uf_matriz'] = market.loc[market['sg_uf_matriz'].isna(), 'sg_uf']
market['de_nivel_atividade'].fillna('MUITO BAIXA',inplace=True)
market['de_saude_tributaria'].fillna('VERMELHO',inplace=True)

In [9]:
market['idade_media_socios'].fillna(market['idade_media_socios'].median(), inplace=True)
market['empsetorcensitariofaixarendapopulacao'].fillna(market['empsetorcensitariofaixarendapopulacao'].median(), inplace=True)

### Feature Engineering

In [10]:
market['porc_st_regular'] = market['qt_socios_st_regular']/market['qt_socios']

In [11]:
market['socio_pep'] = 0
market.loc[market['qt_socios_pep'] > 0, 'socio_pep'] = 1

In [12]:
market['coligada_exterior'] = 0
market.loc[market['qt_coligados_exterior'] > 0, 'coligada_exterior'] = 1

In [13]:
market['porc_socios_pf'] = market['qt_socios_pf']/market['qt_socios']
market['porc_socios_pj'] = market['qt_socios_pj']/market['qt_socios']

### Tratamento de Outliers

In [14]:
market = market[market['idade_media_socios'] > 0]

In [15]:
market = market[market['vl_faturamento_estimado_aux'] < 10000000000]

### Corte de features que sobraram com mais de 50% de valores missing

In [16]:
features = aux[aux.percentual > 0.5].index
len(features)

39

In [17]:
market = market[features]
market.drop('qt_socios_st_regular',1, inplace=True)
market.drop(['qt_socios_pj','qt_socios_pf'], 1, inplace=True)

In [18]:
market.head()

,id,fl_matriz,sg_uf,natureza_juridica_macro,setor,idade_empresa_anos,fl_me,fl_sa,fl_epp,fl_mei,fl_ltda,fl_st_especial,fl_email,fl_telefone,fl_rm,nm_segmento,fl_spa,fl_antt,fl_veiculo,fl_optante_simples,vl_total_veiculos_pesados_grupo,vl_total_veiculos_leves_grupo,fl_optante_simei,sg_uf_matriz,de_saude_tributaria,nu_meses_rescencia,de_nivel_atividade,fl_simples_irregular,empsetorcensitariofaixarendapopulacao,nm_meso_regiao,fl_passivel_iss,qt_socios,idade_media_socios,vl_faturamento_estimado_aux,vl_faturamento_estimado_grupo_aux,qt_filiais
0,a6984c3ae395090e3bee8ad63c3758b110de096d5d8195...,True,RN,ENTIDADES EMPRESARIAIS,CONSTRU√á√ÉO CIVIL,14.457534,False,False,False,False,False,False,True,True,SIM,CONSTRUCAO,False,False,False,True,0.0,0.0,False,RN,VERDE,23.0,ALTA,False,946.68,LESTE POTIGUAR,True,2.0,44.0,3132172.8,3132172.8,0
1,6178f41ade1365e44bc2c46654c2c8c0eaae27dcb476c4...,True,PI,OUTROS,SERVI√áO,1.463014,False,False,False,True,False,False,True,True,SIM,ALOJAMENTO E ALIMENTACAO,False,False,False,False,0.0,0.0,False,PI,CINZA,9.0,BAIXA,False,468.93,CENTRO NORTE PIAUIENSE,True,1.0,27.0,210000.0,210000.0,0
2,4a7e5069a397f12fdd7fd57111d6dc5d3ba558958efc02...,True,AM,OUTROS,SERVI√áO,7.093151,False,False,False,True,False,False,False,True,SIM,TRANSPORTE ARMAZENAGEM E CORREIO,False,False,False,True,0.0,0.0,True,AM,AMARELO,26.0,MEDIA,False,713.50,CENTRO AMAZONENSE,True,1.0,32.0,50000.0,50000.0,0
3,3348900fe63216a439d2e5238c79ddd46ede454df7b9d8...,True,AM,OUTROS,SERVI√áO,6.512329,False,False,False,False,False,False,True,True,SIM,OUTRAS ATIVIDADES DE SERVICOS,False,False,False,True,0.0,0.0,False,AM,AMARELO,26.0,MEDIA,False,475.73,CENTRO AMAZONENSE,True,1.0,36.0,210000.0,210000.0,0
4,1f9bcabc9d3173c1fe769899e4fac14b053037b953a1e4...,True,RN,OUTROS,SERVI√áO,3.200000,False,False,False,False,False,False,True,True,SIM,ATIVIDADES PROFISSIONAIS CIENTIFICAS E TECNICAS,False,False,False,True,0.0,0.0,False,RN,VERDE,27.0,ALTA,False,2874.04,LESTE POTIGUAR,True,1.0,42.0,210000.0,210000.0,0

In [19]:
market.isnull().sum()

id                                          0
fl_matriz                                   0
sg_uf                                       0
natureza_juridica_macro                     0
setor                                    1927
idade_empresa_anos                          0
fl_me                                       0
fl_sa                                       0
fl_epp                                      0
fl_mei                                      0
fl_ltda                                     0
fl_st_especial                              0
fl_email                                    0
fl_telefone                                 0
fl_rm                                       0
nm_segmento                              1927
fl_spa                                   1927
fl_antt                                  1927
fl_veiculo                               1927
fl_optante_simples                          0
vl_total_veiculos_pesados_grupo          1927
vl_total_veiculos_leves_grupo            1927
fl_optante_simei                            0
sg_uf_matriz                                0
de_saude_tributaria                         0
nu_meses_rescencia                          0
de_nivel_atividade                          0
fl_simples_irregular                     1927
empsetorcensitariofaixarendapopulacao       0
nm_meso_regiao                              0
fl_passivel_iss                          1927
qt_socios                                   0
idade_media_socios                          0
vl_faturamento_estimado_aux                 0
vl_faturamento_estimado_grupo_aux           0
qt_filiais                                  0
dtype: int64

In [20]:
market.dropna(inplace=True)

In [21]:
market.to_csv('features.csv')

### Categ√≥ricas

In [22]:
market.loc[market['fl_rm'] == 'NAO', 'fl_rm'] = 0
market.loc[market['fl_rm'] == 'SIM', 'fl_rm'] = 1
market['fl_rm'] = pd.to_numeric(market['fl_rm'])

In [23]:
col_bool = market.dtypes[market.dtypes == 'bool'].index
for col in col_bool:
        market[col] = market[col].astype(int)

In [24]:
cat_cols = market.select_dtypes('object').columns
cat_cols = cat_cols[1:]

market_dummies = pd.get_dummies(market, columns=cat_cols, drop_first=True)

### To CSV

In [25]:
market_dummies.index = market_dummies.id
market_dummies.drop('id',1,inplace=True)

In [26]:
market_dummies.to_csv('pp_market.csv')